[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "enhance"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pyyaml",
    "numpy<2",
    "opencv-python",
    "scikit-image",
    "torch",
    "diffusers>=0.24,<0.30",
    "transformers>=4.31,<4.41",
    "accelerate>=0.25,<0.34",
    "safetensors",
    "pyiqa",
    "pytest",
]

[tool.setuptools.packages.find]
where = ["src"]
